#
#  Copyright 2015 VMware, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

- name: create downloads directory
  file:
    dest: "{{ downloads_dir }}"
    state: directory
    owner: "{{ ansible_ssh_user |default(ansible_user_id) }}"
    group: "{{ ansible_ssh_user |default(ansible_user_id) }}"
    mode: 0755

- name: "get file stats"
  stat: path="{{ downloads_dir }}/{{ item.key }}"
  when: download_files and assets
  register: file_stats
  with_dict: "{{ assets }}"

- name: "pull files as needed (will take many minutes the first time)"
  get_url:
    force: yes
    dest: "{{ downloads_dir }}/{{ item.item.key }}"
    url: "{{ item.item.value.url }}"
    timeout: "{{ downloads_timeout }}"
    validate_certs: "{{ item.item.value.validate_certs | default(assets_validate_certs) }}"
    mode: 0755
  when: download_files and (not item.stat.exists or (item.stat.checksum != item.item.value.checksum))
  with_items: "{{ file_stats.results }}"

- name: Install and setup nginx for http host
  include_role:
    name: jdauphant.nginx
  vars:
    nginx_sites:
      assets_hosting:
        - "listen {{ assets_http_port }}"
        - server_name localhost
        - "root {{ downloads_dir }}"
        - "location / { autoindex on; }"
  when: assets_http_hosted
